# https://spring.pleiades.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
      - "org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration"

server:
  port: 8085

management:
  # https://spring.pleiades.io/spring-boot/reference/actuator/endpoints.html
  endpoints:
    # defaultはオプトアウトで意図しない有効化が行われないようにオプトイン形式に変更する
    enabled-by-default: false
    web:
      exposure:
        # defaultはセキュリティ上の理由でhealthのみ
        # 公開する際はSpringSecurity等によるアクセス保護を行うことが大切
        include: health,scheduledtasks,mappings,metrics
  endpoint:
    health:
      enabled: true
    scheduledtasks:
      enabled: true
    mappings:
      enabled: true
    metrics:
      enabled: true
